name: Ember CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: actions-ember-testing
        uses: ./ # Uses an action in the root directory
        id: actions-ember-testing
        with:
          yarn-version: '1.17'
          node-version: '12'
      - name: Verify node & yarn versions
        run: node -v && yarn -v


