name: Ember CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Volta
        run: |
          curl https://get.volta.sh | bash
          echo 'export VOLTA_HOME=$HOME/.volta' >> ~/.bashrc
          echo 'export PATH=$VOLTA_HOME:$PATH' >> ~/.bashrc
      - name: Debug
        run: cat ~/.bashrc
      - name: Debug 2
        run: cat /home/runner/.bashrc
      - name: Debug path
        run: echo $PATH
      - name: Debug 3
        run: volta -v

